import { describe, expect, it, vi, beforeEach } from "vitest";
import { SettingsService } from "./index";
import { prisma } from "@/lib/db";

vi.mock("@/lib/db", () => ({
  prisma: {
    tenantSettings: {
      findUnique: vi.fn(),
      upsert: vi.fn(),
    },
  },
}));

const mockPrisma = vi.mocked(prisma);

describe("SettingsService", () => {
  const tenantId = 1;

  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe("getSettings", () => {
    it("retorna settings existentes", async () => {
      const mockSettings = {
        id: 1,
        tenantId,
        enableDiscount: true,
        maxDiscount: 10,
        enableStockControl: true,
        allowNegativeStock: false,
        autoGenerateDailyReport: true,
        companyLogoUrl: null,
      };
      mockPrisma.tenantSettings.findUnique.mockResolvedValue(mockSettings);

      const result = await SettingsService.getSettings(tenantId);

      expect(result).toEqual(mockSettings);
    });

    it("retorna defaults quando nao existe settings", async () => {
      mockPrisma.tenantSettings.findUnique.mockResolvedValue(null);

      const result = await SettingsService.getSettings(tenantId);

      expect(result.enableDiscount).toBe(true);
      expect(result.enableStockControl).toBe(true);
      expect(result.allowNegativeStock).toBe(false);
      expect(result.autoGenerateDailyReport).toBe(true);
      expect(result.companyLogoUrl).toBeNull();
    });
  });

  describe("updateSettings", () => {
    it("cria settings via upsert", async () => {
      const mockCreated = {
        id: 1,
        tenantId,
        enableDiscount: false,
        maxDiscount: 15,
        enableStockControl: true,
        allowNegativeStock: false,
        autoGenerateDailyReport: true,
        companyLogoUrl: null,
      };
      mockPrisma.tenantSettings.upsert.mockResolvedValue(mockCreated);

      const result = await SettingsService.updateSettings(tenantId, {
        enableDiscount: false,
        maxDiscount: 15,
      });

      expect(result.enableDiscount).toBe(false);
      expect(result.maxDiscount).toBe(15);
    });

    it("atualiza companyLogoUrl", async () => {
      const mockUpdated = {
        id: 1,
        tenantId,
        enableDiscount: true,
        maxDiscount: null,
        enableStockControl: true,
        allowNegativeStock: false,
        autoGenerateDailyReport: true,
        companyLogoUrl: "https://example.com/logo.png",
      };
      mockPrisma.tenantSettings.upsert.mockResolvedValue(mockUpdated);

      const result = await SettingsService.updateSettings(tenantId, {
        companyLogoUrl: "https://example.com/logo.png",
      });

      expect(result.companyLogoUrl).toBe("https://example.com/logo.png");
    });
  });
});
