"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import type { Role } from "@prisma/client";
import { prisma } from "@/lib/db";
import { requireSessionTenant } from "@/lib/tenant";
import { requirePermission } from "@/lib/permissions";
import { updateTenantSettingsSchema } from "@/lib/validators";

export async function updateSettingsAction(formData: FormData) {
  const { tenant, dbUser } = await requireSessionTenant("/dashboard/configuracoes");
  try {
    requirePermission(dbUser.role as Role, "tenants.manage");
  } catch {
    redirect("/dashboard/configuracoes?error=forbidden");
  }

  const raw = {
    enableDiscount: formData.get("enableDiscount") === "on",
    maxDiscount: formData.get("maxDiscount") ? parseInt(String(formData.get("maxDiscount")), 10) : undefined,
    enableStockControl: formData.get("enableStockControl") === "on",
    allowNegativeStock: formData.get("allowNegativeStock") === "on",
    autoGenerateDailyReport: formData.get("autoGenerateDailyReport") === "on",
  };

  const parsed = updateTenantSettingsSchema.safeParse(raw);
  if (!parsed.success) redirect("/dashboard/configuracoes?error=invalid");

  await prisma.tenantSettings.upsert({
    where: { tenantId: tenant.id },
    update: parsed.data,
    create: { tenantId: tenant.id, ...parsed.data },
  });

  const { logAudit } = await import("@/lib/audit");
  await logAudit({
    tenantId: tenant.id,
    action: "update",
    entity: "settings",
    entityId: tenant.id,
    userId: dbUser.id,
    userEmail: dbUser.email,
    changes: parsed.data,
  });

  revalidatePath("/dashboard/configuracoes");
  redirect("/dashboard/configuracoes?ok=1");
}
