"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import type { Funcao } from "@prisma/client";
import { prisma } from "@/lib/db";
import { requireSessionTenant } from "@/lib/tenant";
import { requirePermission } from "@/lib/permissions";
import { updateTenantSettingsSchema } from "@/lib/validators";
import { ErroImagem, enviarImagemLogo, removerImagemLogo } from "@/lib/storage";

export async function updateSettingsAction(formData: FormData) {
  const { tenant, dbUser } = await requireSessionTenant("/dashboard/configuracoes");
  try {
    requirePermission(dbUser.role as Funcao, "tenants.manage");
  } catch {
    redirect("/dashboard/configuracoes?error=forbidden");
  }

  const feeNum = (v: FormDataEntryValue | null) => {
    if (v === null || String(v).trim() === "") return undefined;
    const n = Number(String(v).replace(",", "."));
    return Number.isFinite(n) ? n : NaN;
  };

  const raw = {
    enableDiscount: formData.get("enableDiscount") === "on",
    maxDiscount: formData.get("maxDiscount") ? parseInt(String(formData.get("maxDiscount")), 10) : undefined,
    enableStockControl: formData.get("enableStockControl") === "on",
    allowNegativeStock: formData.get("allowNegativeStock") === "on",
    autoGenerateDailyReport: formData.get("autoGenerateDailyReport") === "on",
    feeCredit: feeNum(formData.get("feeCredit")),
    feeDebit: feeNum(formData.get("feeDebit")),
  };

  const parsed = updateTenantSettingsSchema.safeParse(raw);
  if (!parsed.success) redirect("/dashboard/configuracoes?error=invalid");

  try {
    await prisma.tenantSettings.upsert({
      where: { tenantId: tenant.id },
      update: parsed.data,
      create: { tenantId: tenant.id, ...parsed.data },
    });
  } catch (e) {
    console.error("[updateSettingsAction] falha inesperada", {
      tenantId: tenant.id,
      cause: e instanceof Error ? e.message : String(e),
    });
    redirect("/dashboard/configuracoes?error=fail");
  }

  const { logAudit } = await import("@/lib/audit");
  await logAudit({
    tenantId: tenant.id,
    action: "update",
    entity: "settings",
    entityId: tenant.id,
    userId: dbUser.id,
    userEmail: dbUser.email,
    changes: parsed.data,
  });

  revalidatePath("/dashboard/configuracoes");
  redirect("/dashboard/configuracoes?ok=1");
}

/**
 * Upload do logo da empresa (Fase 3.3 — PDF com logo da loja).
 *
 * ## Por que upload e não campo de URL
 *
 * O campo de URL que existia pedia que o cliente hospedasse a imagem por conta
 * própria e colasse o link. Numa tela de configuração de loja, isso é uma
 * tarefa que o dono da loja não consegue fazer sozinho — e a URL acabava
 * vazia na maioria das contas, que é a mesma coisa que não ter logo.
 *
 * ## Por que a URL continua existindo no banco
 *
 * `TenantSettings.companyLogoUrl` guarda a URL pública, como `Product.imageUrl`.
 * Ela deixa de ser entrada digitada e vira consequência do upload. Um PDF é
 * gerado no browser e não pode consultar o banco, então a URL precisa estar no
 * registro — guardá-la é o que permite o `ReportActions` desenhar a logo sem
 * fetch extra.
 */
export async function uploadCompanyLogoAction(formData: FormData) {
  const { tenant, dbUser } = await requireSessionTenant("/dashboard/configuracoes");
  try {
    requirePermission(dbUser.role as Funcao, "tenants.manage");
  } catch {
    redirect("/dashboard/configuracoes?error=forbidden");
  }

  const file = formData.get("logo");
  if (!(file instanceof File) || file.size === 0) {
    redirect("/dashboard/configuracoes?error=arquivo");
  }

  let url: string;
  try {
    const { createServiceClient } = await import("@/lib/supabase/service");
    url = await enviarImagemLogo({
      storage: createServiceClient().storage,
      tenantId: tenant.id,
      file,
    });
  } catch (e) {
    if (e instanceof ErroImagem) {
      if (e.codigo === "TIPO" || e.codigo === "TAMANHO" || e.codigo === "VAZIA") {
        redirect("/dashboard/configuracoes?error=arquivo");
      }
      if (e.codigo === "ENVIO") redirect("/dashboard/configuracoes?error=storage");
    }
    console.error("[uploadCompanyLogoAction] falha inesperada", {
      tenantId: tenant.id,
      cause: e instanceof Error ? e.message : String(e),
    });
    redirect("/dashboard/configuracoes?error=fail");
  }

  const anterior = (
    await prisma.tenantSettings.findUnique({
      where: { tenantId: tenant.id },
      select: { companyLogoUrl: true },
    })
  )?.companyLogoUrl;

  try {
    await prisma.tenantSettings.upsert({
      where: { tenantId: tenant.id },
      // upsert: a loja pode não ter linha de settings ainda, e o primeiro
      // upload é justamente o caso de quem nunca abriu Configurações.
      update: { companyLogoUrl: url },
      create: { tenantId: tenant.id, companyLogoUrl: url },
    });
  } catch (e) {
    console.error("[uploadCompanyLogoAction] falha ao gravar a URL", {
      tenantId: tenant.id,
      cause: e instanceof Error ? e.message : String(e),
    });
    redirect("/dashboard/configuracoes?error=fail");
  }

  // A logo antiga só é removida depois que a nova está gravada: se a gravação
  // falhar, o operador continua com a logo que já funcionava. Sem espaço no
  // bucket, cada troca deixaria um arquivo órfão.
  if (anterior && anterior !== url) {
    try {
      const { createServiceClient } = await import("@/lib/supabase/service");
      await removerImagemLogo({
        storage: createServiceClient().storage,
        tenantId: tenant.id,
        url: anterior,
      });
    } catch (e) {
      console.error("[uploadCompanyLogoAction] limpeza do logo antigo falhou", {
        tenantId: tenant.id,
        cause: e instanceof Error ? e.message : String(e),
      });
    }
  }

  const { logAudit } = await import("@/lib/audit");
  await logAudit({
    tenantId: tenant.id,
    action: "update",
    entity: "settings",
    entityId: tenant.id,
    userId: dbUser.id,
    userEmail: dbUser.email,
    changes: { companyLogoUrl: url, substituiu: anterior ?? null },
    details: "Logo da empresa atualizada para aparecer nos PDF e recibos.",
  });

  // As 5 telas que geram PDF leem o logo do settings; sem revalidar, uma logo
  // nova só apareceria depois de um hard reload.
  revalidatePath("/dashboard/configuracoes");
  revalidatePath("/dashboard/relatorios");
  revalidatePath("/dashboard/financeiro");
  revalidatePath("/dashboard/estoque");
  revalidatePath("/dashboard/auditoria");
  redirect("/dashboard/configuracoes?ok=logo");
}
