import { redirect } from "next/navigation";
import type { Role } from "@prisma/client";
import { prisma } from "@/lib/db";
import { requireSessionTenant } from "@/lib/tenant";
import { requirePermission } from "@/lib/permissions";
import { PageHeader } from "@/components/shared/PageHeader";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { SwitchField } from "@/components/ui/switch-field";
import { Separator } from "@/components/ui/separator";
import { updateSettingsAction } from "./actions";

const ERROR_MSG: Record<string, string> = {
  invalid: "Dados inválidos.",
  forbidden: "Seu role não tem permissão para alterar configurações.",
};

export default async function ConfiguracoesPage({
  searchParams,
}: {
  searchParams: Promise<{ error?: string; ok?: string }>;
}) {
  const { tenant, dbUser } = await requireSessionTenant("/dashboard/configuracoes");
  try {
    requirePermission(dbUser.role as Role, "tenants.manage");
  } catch {
    redirect("/unauthorized");
  }
  const params = await searchParams;
  const settings =
    (await prisma.tenantSettings.findUnique({ where: { tenantId: tenant.id } })) ?? {
      enableDiscount: true,
      maxDiscount: null as number | null,
      enableStockControl: true,
      allowNegativeStock: false,
      autoGenerateDailyReport: true,
    };

  return (
    <main className="mx-auto flex w-full max-w-5xl flex-1 flex-col gap-6 px-6 py-8">
      <PageHeader
        title="Configurações"
        badge={tenant.name}
        description="Regras da conveniência."
      />

      <Card>
        <CardHeader>
          <CardTitle>Regras de operação</CardTitle>
        </CardHeader>
        <CardContent>
          <form action={updateSettingsAction} className="flex flex-col gap-4">
            <SwitchField name="enableDiscount" defaultChecked={settings.enableDiscount} label="Permitir desconto em vendas" />
            <label className="flex flex-col gap-1 text-sm">
              Desconto máximo (%)
              <Input
                name="maxDiscount"
                type="number"
                min={0}
                max={100}
                defaultValue={settings.maxDiscount ?? ""}
                placeholder="Ex.: 10"
              />
            </label>
            <Separator />
            <SwitchField name="enableStockControl" defaultChecked={settings.enableStockControl} label="Controlar estoque (bloqueia venda sem saldo)" />
            <SwitchField name="allowNegativeStock" defaultChecked={settings.allowNegativeStock} label="Permitir estoque negativo" />
            <Separator />
            <SwitchField
              name="autoGenerateDailyReport"
              defaultChecked={(settings as { autoGenerateDailyReport?: boolean }).autoGenerateDailyReport ?? true}
              label="Gerar relatório diário automaticamente"
            />
            {params.error ? (
              <p className="text-sm text-destructive">{ERROR_MSG[params.error] ?? "Erro ao salvar."}</p>
            ) : null}
            {params.ok ? <p className="text-sm text-muted-foreground">Salvo com sucesso.</p> : null}
            <Button type="submit">Salvar</Button>
          </form>
        </CardContent>
      </Card>
    </main>
  );
}
