import { redirect } from "next/navigation";
import type { Funcao } from "@prisma/client";
import { prisma } from "@/lib/db";
import { requireSessionTenant } from "@/lib/tenant";
import { requirePermission } from "@/lib/permissions";
import { PageHeader } from "@/components/shared/PageHeader";
import { SearchParamToast } from "@/components/shared/SearchParamToast";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { SwitchField } from "@/components/ui/switch-field";
import { Separator } from "@/components/ui/separator";
import { updateSettingsAction } from "./actions";
import { CompanyLogoField } from "./company-logo-field";

const ERROR_MSG: Record<string, string> = {
  invalid: "Dados inválidos.",
  forbidden: "Seu role não tem permissão para alterar configurações.",
  arquivo: "Logo inválida. Use JPG ou PNG de até 512KB.",
  storage: "Não foi possível guardar o arquivo. Tente novamente.",
  fail: "Não foi possível salvar. Tente novamente.",
};

export default async function ConfiguracoesPage() {
  const { tenant, dbUser } = await requireSessionTenant("/dashboard/configuracoes");
  try {
    requirePermission(dbUser.role as Funcao, "tenants.manage");
  } catch {
    redirect("/unauthorized");
  }
  const settings =
    (await prisma.tenantSettings.findUnique({ where: { tenantId: tenant.id } })) ?? {
      enableDiscount: true,
      maxDiscount: null as number | null,
      enableStockControl: true,
      allowNegativeStock: false,
      autoGenerateDailyReport: true,
      companyLogoUrl: null as string | null,
      feeCredit: 0,
      feeDebit: 0,
    };

  return (
    <main className="mx-auto flex w-full max-w-6xl flex-1 flex-col gap-6 px-6 py-8">
      <PageHeader
        title="Configurações"
        badge={tenant.name}
        description="Regras da conveniência."
      />
      <SearchParamToast okText="Salvo com sucesso." errorMap={ERROR_MSG} />

      <Card>
        <CardHeader>
          <CardTitle>Regras de operação</CardTitle>
        </CardHeader>
        <CardContent>
          <form action={updateSettingsAction} className="flex flex-col gap-3">
            <SwitchField name="enableDiscount" defaultChecked={settings.enableDiscount} label="Permitir desconto em vendas" />
            <label className="flex flex-col gap-1 text-sm">
              Desconto máximo (%)
              <Input
                name="maxDiscount"
                type="number"
                min={0}
                max={100}
                defaultValue={settings.maxDiscount ?? ""}
                placeholder="Ex.: 10"
              />
            </label>
            <Separator />
            <SwitchField name="enableStockControl" defaultChecked={settings.enableStockControl} label="Controlar estoque (bloqueia venda sem saldo)" />
            <SwitchField name="allowNegativeStock" defaultChecked={settings.allowNegativeStock} label="Permitir estoque negativo" />
            <Separator />
            <SwitchField
              name="autoGenerateDailyReport"
              defaultChecked={(settings as { autoGenerateDailyReport?: boolean }).autoGenerateDailyReport ?? true}
              label="Gerar relatório diário automaticamente"
            />
            <Separator />
            <p className="text-sm font-semibold">Taxa maquineta (%)</p>
            <p className="text-xs text-muted-foreground -mt-3">
              Acréscimo cobrado do cliente no cartão. No financeiro entra como DESPESA separada, fora do total da venda.
            </p>
            <div className="grid gap-3 sm:grid-cols-2">
              <label className="flex flex-col gap-1 text-sm">
                Crédito (%)
                <Input
                  name="feeCredit"
                  type="number"
                  min={0}
                  max={100}
                  step="0.01"
                  defaultValue={(settings as { feeCredit?: number }).feeCredit ?? 0}
                  placeholder="Ex.: 2.99"
                />
              </label>
              <label className="flex flex-col gap-1 text-sm">
                Débito (%)
                <Input
                  name="feeDebit"
                  type="number"
                  min={0}
                  max={100}
                  step="0.01"
                  defaultValue={(settings as { feeDebit?: number }).feeDebit ?? 0}
                  placeholder="Ex.: 1.99"
                />
              </label>
            </div>
            <Separator />
            <CompanyLogoField
              currentUrl={(settings as { companyLogoUrl?: string | null }).companyLogoUrl ?? null}
            />
            <Button type="submit">Salvar</Button>
          </form>
        </CardContent>
      </Card>
    </main>
  );
}
